# Generated by Django 3.1.4 on 2021-01-27 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.store'),
        ),
    ]
