# Generated by Django 3.1.5 on 2021-01-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='store',
            name='thumbnail',
        ),
    ]
