# Generated by Django 3.1.4 on 2021-01-27 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210127_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='is_activated_by_admin',
            new_name='is_activated',
        ),
    ]
