# Generated by Django 3.1.5 on 2021-01-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
    ]
